config/routes.rb
Rails.application.routes.draw do
  get "/books", to: "books#index"
  get "/books/new", to: "books#new", as: "new_books"
  post "/books", to: "books#create"
  get "/books/:id" , to: "books#show", as: "book"
  delete "/books/:id", to: "books#destroy"
  get "/books/:id/edit", to: "books#edit", as: "edit_book"
  patch "/books/:id", to: "books#update"
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :date, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :page, numericality: {greater_than_or_equal_to: 0}
  validates :ISBN, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "新增成功"
    else
      render :new
    end
  end

  def show
    begin
      @book = Book.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render html: "404"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path,notice: "刪除成功"
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: "更新成功"
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :date, :price, :page, :ISBN)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<li>
  <%= link_to book.title, book_path(book) %>
  |
  <%= link_to 'X', book_path(book), method: :delete, data: { confirm: "確定嗎？" } %>
</li>

app/views/books/edit.html.erb
<h1>編輯詳細資訊</h1>

<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :title, "書名:" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :date, "出版日期:" %>
    <%= form.date_field :date, max: Date.today %>
  </div>
  <div>
    <%= form.label :price, "售價:" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :page, "頁數:" %>
    <%= form.text_field :page %>
  </div>
  <div>
    <%= form.label :ISBN, "ISBN:" %>
    <%= form.text_field :ISBN %>
  </div>
  <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<h1>書列表</h1>
<%= link_to '新增書籍', new_books_path %>
<ul>

  <%= render collection: @books, partial: "books/book" %>
</ul>

app/views/books/new.html.erb
<h1>新增書籍</h1>
<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :title, "書名:" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :date, "出版日期:" %>
    <%= form.date_field :date, max: Date.today %>
  </div>
  <div>
    <%= form.label :price, "售價:" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :page, "頁數:" %>
    <%= form.text_field :page %>
  </div>
  <div>
    <%= form.label :ISBN, "ISBN:" %>
    <%= form.text_field :ISBN %>
  </div>
  <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<ul>
  <li>出版日期：<%= @book.date %></li>
  <li>售價：<%= @book.price %></li>
  <li>頁數：<%= @book.page %></li>
  <li>ISBN:<%= @book.ISBN %></li>
</ul>

<%= link_to '編輯', edit_book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'share/flash' %>
    <%= yield %>
  </body>
</html>

app/views/share/_flash.html.erb
<%= notice %>